version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    volumes:
      - /var/log/nginx:/var/log/nginx
    env_file:
      - .dev.env
    ports:
      - '80:80'

  redis:
    image: redis:3.2.0
    container_name: redis
    ports:
      - '6379:6379'
  
  sidekiq:
    build: .
    links:
      - redis
      - postgres
    volumes:
      - .:/app
    env_file:
      - .dev.env
    command: bundle exec sidekiq -C config/sidekiq.yml

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/myapp
      - /var/run/app-socket:/var/run/app-socket
    links:
      - postgres
      - redis
    depends_on:
      - postgres
    env_file:
      - .dev.env
    ports:
      - 3000:3000

  postgres:
    image: postgres:9.5.3
    container_name: postgres
    volumes:
      - /var/lib/docker/volumes/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .dev.env