version: '3'

services:  
  app:    
    build:      
      context: .      
      dockerfile: ./docker/app/Dockerfile  
    volumes:
      - .:/rails_todo 
    depends_on:      
      - db  
    env_file:
      - app.env
    ports:      
      - 3000:3000
      
  db:    
    image: postgres:9.5  
    volumes:      
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    env_file:
      - db.env
    ports:      
      - 5432:5432

  web:    
    build:      
      context: .
      dockerfile: ./docker/web/Dockerfile   
    depends_on:      
      - app    
    ports:      
      - 80:80